const lang = {
    BOTH_MODE_NOT_PERMITTED: "Cannot activate both presale and fairlaunch mode!",
    INVALID_DELAY_OPTION: "You must pass an int (number of blocks) as delay value!",
    OPTIONS_ERROR: "An error occurred while reading options. Please check documentation.",
    FAIR_TBD: "Sorry, fairlaunch mode is still under development.",
    SHOW_BOT_SETTINGS: "You have launched the bot with the following settings: ",
    MODE: "Mode",
    DELAY: "Delay",
    NET: "Net",
    BLOCKS: "blocks",
    CHANGE_DELAY: "Do you want to change number of delay blocks? (y/n): ",
    INVALID_DELAY_INPUT: "Only integers accepted. Insert number of delay blocks: ",
    YOU_DIGITED: "You digited ",
    CONFIRM: "Confirm? (y/n): ",
    INSERT_DELAY: "Insert number of delay blocks: ",
    DELAY_CHANGED: "Delay blocks number has been changed to ",
    DELAY_NOT_CHANGED: "Delay blocks number has not been changed.",
    ONLY_Y_OR_N: "digit only y or n: ",
    SHOW_NEW_WALLET_CONF: "Here's the new wallet configuration:",
    WALLET_CONFIG_ERROR: "It seems that something went wrong during the wallet configuration.",
    CHECKING_WALLET_CONF: "Checking wallet configuration...",
    WALLET_CONFIG_FOUND: "Found the following wallet configuration: ",
    CHANGE_WALLET_CONF: "Do you want to change wallet configuration? (y/n): ",
    STARTING_WALLET_CONF: "Starting configuration procedure now.",
    INSERT: "Insert ",
    ADDR_NOT_VALID: "Address is not valid.",
    PVT_KEY_NOT_VALID: "A key is not valid.",
    INSERT_START_HOUR: "Insert start hour: ",
    NAN: "Not a number. ",
    HOUR_RANGE: "Must be a number between 0 and 23. ",
    INSERT_START_MINUTE: "Insert start minute: ",
    MINUTE_RANGE: "Must be a number between 0 and 59. ",
    INITIALIZING_PRESALE_BOT: "Starting presale bot with the chosen settings...",
    WILL_ASK_TIME: "You will now be asked for time of presale start. Please, use your ",
    LOCAL_TIME: "LOCAL TIME",
    START_TIME_SET: "Time of presale start has been set to ",
    ERROR_OCCURRED: "The following error occurred: ",
    TRANSACTION_SUCCESSFUL: "Transaction sent successfully. ",
    TX_HASH: "Transacion hash: ",
    WAITING: "Waiting for time to come...",
    ARMED: "Bot armed.",
    ASK_TARGET_ADDR: "Insert target address: ",
    TODAY_OR_TOMORROW: "The bot will snipe at the given time today. Do you want to set it to snipe tomorrow instead? (y/n): ",
    BLOCK_QUERY_ERR: "Error occurred quering the block",
    EOR: "End of error",
    SHOULD_NOT_INTERFER: "NOTE: If the error occurs occasionally the bot should still continue running smoothly",
    CHOOSE_PAIR: "Choose the pair; digit 1 for bnb or 2 for busd: ",
    PAIR_NOT_VALID: "Not valid. Digit 1 for bnb or 2 for busd: ",
    WAITING_PAIR: "Waiting for pair to be created...",
    WAITING_LIQ: "Liquidity pool now exists. Waiting for liquidity to be added...",
    LIQ_ADDED_TRYING_SWAP: "Liquidity found, trying swap...",
    LIQ_ADDED_WAITING: "Liquidity found, waiting the desired number of blocks...",
    WAITING_BLOCKCHAIN_CONFIRM: "Waiting for blockchain confirmation...",
    TX_CONFIRMED: "Transaction confirmed.",
    TX_ERROR: "Error during transaction execution. Details will follow."
};
export default {lang}