const lang = {
    BOTH_MODE_NOT_PERMITTED: "Non puoi attivare le modalità presale e fairlaunch contemporaneamente!",
    INVALID_DELAY_OPTION: "Devi passare un numero intero come numero di blocchi di attesa!",
    OPTIONS_ERROR: "C'è stato un errore nella lettura delle opzioni. Cortesemente, controlla la documentazione.",
    FAIR_TBD: "Mi dispiace, la modalità fairlaunch è ancora in via di sviluppo.",
    SHOW_BOT_SETTINGS: "Hai avviato il bot con le seguenti impostazioni: ",
    MODE: "Modalità",
    DELAY: "Attesa",
    NET: "Net",
    BLOCKS: "blocchi",
    CHANGE_DELAY: "Vuoi cambiare il numero di blocchi di attesa? (y/n): ",
    INVALID_DELAY_INPUT: "Ammessi solo numeri interi. Inserire numero di blocchi di attesa: ",
    YOU_DIGITED: "Hai digitato ",
    CONFIRM: "Confermi? (y/n): ",
    INSERT_DELAY: "Inserire numero di blocchi di attesa: ",
    DELAY_CHANGED: "Numero di blocchi di attesa cambiato a ",
    DELAY_NOT_CHANGED: "Numero di blocchi di attesa non cambiato.",
    ONLY_Y_OR_N: "digitare solo y o n: ",
    SHOW_NEW_WALLET_CONF: "Ecco la nuova configurazione del wallet:",
    WALLET_CONFIG_ERROR: "Sembra che qualcosa sia andato storto durante la configurazione del wallet.",
    CHECKING_WALLET_CONF: "Controllando la configurazione del wallet...",
    WALLET_CONFIG_FOUND: "Trovata la seguente configurazione per il wallet: ",
    CHANGE_WALLET_CONF: "Vuoi cambiare la configurazione del wallet? (y/n): ",
    STARTING_WALLET_CONF: "Inizio la procedura di configurazione ora.",
    INSERT: "Inserire ",
    ADDR_NOT_VALID: "Indirizzo non valido.",
    PVT_KEY_NOT_VALID: "Una private key non è valida.",
    INSERT_START_HOUR: "Inserire l'ora di inizio: ",
    NAN: "Non è un numero. ",
    HOUR_RANGE: "Deve essere un numero tra 0 e 23. ",
    INSERT_START_MINUTE: "Inserire il minuto di inizio: ",
    MINUTE_RANGE: "Deve essere un numero tra 0 e 59. ",
    INITIALIZING_PRESALE_BOT: "Avviando il bot presale con le impostazioni selezionate...",
    WILL_ASK_TIME: "Ti verrà chiesto di inserire l'orario di inizio della presale. Usare l' ",
    LOCAL_TIME: "ORARIO LOCALE",
    START_TIME_SET: "Orario di inzio della presale impostato a ",
    ERROR_OCCURRED: "Si è sollevato il seguente errore: ",
    TRANSACTION_SUCCESSFUL: "Transazione emessa con successo. ",
    TX_HASH: "Hash della transazione: ",
    WAITING: "Attendendo l'orario di inizio...",
    ARMED: "Bot armato.",
    ASK_TARGET_ADDR: "Inserire indirizzo bersaglio: ",
    TODAY_OR_TOMORROW: "Il bot effettuerà lo sniping oggi all'ora selezionata. Vuoi invece impostarlo per effettuare lo sniping domani? (y/n): ",
    BLOCK_QUERY_ERR: "C'è stato un errore nella richiesta del blocco",
    EOR: "Fine errore",
    SHOULD_NOT_INTERFER: "NOTA: Se l'errore viene sollevato occasionalmente il bot dovrebbe poter ancora continuare a lavorare in tranquillità.",
    CHOOSE_PAIR: "Scegliere la coppia; digitare 1 per bnb o 2 per busd: ",
    PAIR_NOT_VALID: "Non valido; digitare 1 per bnb o 2 per busd: ",
    WAITING_PAIR: "Aspettando che la coppia venga creata...",
    WAITING_LIQ: "Pool di liquidità creata. aspettando che la liquidità venga immessa...",
    LIQ_ADDED_TRYING_SWAP: "C'è liquidita, provo lo swap...",
    LIQ_ADDED_WAITING: "C'è liquidità, aspetto il numero di blocchi desiderato...",
    WAITING_BLOCKCHAIN_CONFIRM: "Aspettando conferma dalla blockchain...",
    TX_CONFIRMED: "Transazione confermata.",
    TX_ERROR: "Errore durante l'esecuzione della transazione. Di seguito i dettagli."
};
export default {lang}